name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html pytest-playwright
        playwright install

    # Run tests
    - name: Run E2E tests
      run: |
        pytest -n auto --html=reports/report.html --self-contained-html

    # Upload HTML report as artifact
    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: reports/report.html
